### ISSUE TITLE
run midi_to_str.py error

### ISSUE THREAD

**Issue by Seven-pence** [briansemrau/MIDI-LLM-tokenizer#3]
(musicllm) C:\Protable Program\MIDI-LLM-tokenizer>python ./midi_to_str.py test.mid
Traceback (most recent call last):
  File "C:\Protable Program\MIDI-LLM-tokenizer\midi_to_str.py", line 6, in <module>
    import midi_util
  File "C:\Protable Program\MIDI-LLM-tokenizer\midi_util.py", line 12, in <module>
    class VocabConfig:
  File "C:\Users\Origami\.conda\envs\musicllm\lib\dataclasses.py", line 1184, in dataclass
    return wrap(cls)
  File "C:\Users\Origami\.conda\envs\musicllm\lib\dataclasses.py", line 1175, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "C:\Users\Origami\.conda\envs\musicllm\lib\dataclasses.py", line 1024, in _process_class
    _init_fn(all_init_fields,
  File "C:\Users\Origami\.conda\envs\musicllm\lib\dataclasses.py", line 544, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'do_token_sorting' follows default argument

**Comment by briansemrau** [comment]
make sure you're on the latest version.

**Comment by briansemrau** [comment]
closing, I believe this issue was already fixed.
